[package]
name = "yass_lib"
version = "0.1.0"
edition = "2021"
authors = ["Marty3000"]
description = "Yet another sudoku solver"
license = "MIT"
repository = "https://github.com/Marty3000/yass.git"
documentation = "https://docs.rs/yass"
keywords = ["sudoku"]
categories = ["games"]

[dependencies]
